/**
 * ACTION TYPES
 */
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY'
export const CLEAR_ORDER_HISTORY = 'CLEAR_ORDER_HISTORY'
export const REMOVE_ORDER_HISTORY = 'REMOVE_ORDER_HISTORY'
export const ADD_ORDER_HISTORY = 'ADD_ORDER_HISTORY'
export const FETCH_ORDER_HISTORY = 'FETCH_ORDER_HISTORY'
